name: CI
on: [push]
jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: andresz1/size-limit-action@v1
        with:
          skip_step: build
          github_token: ${{ secrets.GITHUB_TOKEN }}